name: Frontend CI/CD

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout Source Code
    - name: Checkout
      uses: actions/checkout@v3

    # Install OpenVPN
    - name: Install OpenVPN
      run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

    # Connect to VPN
    - name: Connect to VPN
      uses: kota65535/github-openvpn-connect-action@v2
      with:
          config_file: .github/workflows/sitst-client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}

    # Debug Context: List Files
    - name: Debug Build Context
      run: ls -la /

    # Build and Push Docker Image
    - name: Build and Push Docker Image
      env:
        IMAGE_NAME: wachrawit/my-frontend-app
        IMAGE_TAG: ${{ github.event.inputs.branch }}
      run: |
        # Login to Docker Hub
        echo "Logging in to Docker Hub..."
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        # Build Docker Image
        echo "Building Docker image $IMAGE_NAME:$IMAGE_TAG..."
        docker build -f /Dockerfile \
          -t $IMAGE_NAME:$IMAGE_TAG \
          /

        # Push Docker Image to Docker Hub
        echo "Pushing Docker image to Docker Hub..."
        docker push $IMAGE_NAME:$IMAGE_TAG

      # Deploy via SSH
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          IMAGE_NAME=wachrawit/my-frontend-app
          IMAGE_TAG=${{ github.event.inputs.branch }}

          # Login to Docker Hub
          echo "Logging into Docker Hub..."
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Stop and Remove Old Container by Name
          echo "Stopping and removing old container by name..."
          docker stop my-frontend-app || true && docker rm my-frontend-app || true

          # Remove Old Docker Image
          echo "Removing old Docker image..."
          docker rmi -f $IMAGE_NAME:$IMAGE_TAG || echo "No previous image found."

          # Pull Docker Image
          echo "Pulling latest Docker image..."
          docker pull $IMAGE_NAME:$IMAGE_TAG

          # Prune Dangling Images (Optional)
          echo "Cleaning up unused Docker images..."
          docker image prune -f

          # Start New Container
          echo "Starting new container..."
          docker run -d --name my-frontend-app \
            -p 3001:3000 \
            $IMAGE_NAME:$IMAGE_TAG
          echo "Deployment complete!"

# name: Frontend CI/CD

# on:
#   workflow_dispatch:
#     inputs:
#       branch:
#         description: 'Branch to deploy'
#         required: true
#         default: 'main'

# jobs:
#   frontend-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       # Checkout Source Code
#       - name: Checkout
#         uses: actions/checkout@v3

#       # Install OpenVPN
#       - name: Install OpenVPN
#         run: |
#           sudo apt update
#           sudo apt install -y openvpn openvpn-systemd-resolved

#       # Connect to VPN
#       - name: Connect to VPN
#         uses: kota65535/github-openvpn-connect-action@v2
#         with:
#           config_file: .github/workflows/sitst-client.ovpn
#           username: ${{ secrets.OVPN_USERNAME }}
#           password: ${{ secrets.OVPN_PASSWORD }}

#       # Build and Push Docker Image
#       - name: Build and Push Frontend Docker Image
#         env:
#           IMAGE_NAME: pongpairoch/my-frontend-app
#           IMAGE_TAG: ${{ github.event.inputs.branch }}
#         run: |
#           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#           docker build -f CP24NW1-web-admin-frontend/web-admin/Dockerfile \
#             -t $IMAGE_NAME:$IMAGE_TAG \
#             CP24NW1-web-admin-frontend/web-admin

#           docker push $IMAGE_NAME:$IMAGE_TAG

#       # Deploy via SSH
#       - name: Deploy Frontend
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           password: ${{ secrets.SSH_PASSWORD }}
#           script: |
#             IMAGE_NAME=pongpairoch/my-frontend-app
#             IMAGE_TAG=${{ github.event.inputs.branch }}

#             echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#             docker stop my-frontend-app || true && docker rm my-frontend-app || true

#             docker rmi -f $IMAGE_NAME:$IMAGE_TAG || true

#             docker pull $IMAGE_NAME:$IMAGE_TAG

#             docker image prune -f

#             docker run -d --name my-frontend-app \
#               -p 3001:3000 \
#               $IMAGE_NAME:$IMAGE_TAG
